### ISSUE TITLE
uploadSymbolsToBugsnag() is not detecting dsymPath

### ISSUE THREAD

**Issue by RyuX51** [bugsnag/bugsnag-dsym-upload#66]
Hi there, 

is Swift officially supported now? `uploadSymbolsToBugsnag()` is not detecting the `dsymPath` in my setup. Neither the files in the current directory nor through invocation of `downloadDsyms` before.

```
func refreshDsymsLane() {
    downloadDsyms(username: "m***@***.com", appIdentifier: "com.vjeton.diamond")
    uploadSymbolsToBugsnag(apiKey: "71b**************867")
    cleanBuildArtifacts()
  }
```
 
Result:

```
INFO [2021-08-26 22:24:20.10]: ---------------------------------------
INFO [2021-08-26 22:24:20.10]: --- Step: upload_symbols_to_bugsnag ---
INFO [2021-08-26 22:24:20.10]: ---------------------------------------
DEBUG [2021-08-26 22:24:20.10]: Uploading dSYMs to Bugsnag with the following parameters:
DEBUG [2021-08-26 22:24:20.10]:              api_key: 71b**************867
DEBUG [2021-08-26 22:24:20.10]:            dsym_path: []
DEBUG [2021-08-26 22:24:20.10]:         project_root: /Users/mario/Repository/VJeton
DEBUG [2021-08-26 22:24:20.10]:           upload_url:
DEBUG [2021-08-26 22:24:20.10]:     symbol_maps_path:
DEBUG [2021-08-26 22:24:20.10]:   ignore_missing_dwarf: false
DEBUG [2021-08-26 22:24:20.10]:    ignore_empty_dsym: false
DEBUG [2021-08-26 22:24:20.10]:          config_file:
DEBUG [2021-08-26 22:24:20.10]: return_value_type is nil value: []
DEBUG [2021-08-26 22:24:20.10]: sending {"payload":{"status":"ready_for_next","return_object":[],"closure_argument_value":""}}
DEBUG [2021-08-26 22:24:20.10]: received done signal shutting down

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | download_dsyms            | 20          |
| 2    | upload_symbols_to_bugsnag | 0           |
+------+---------------------------+-------------+
```

When I try to set it manually, it works. Example:

```
uploadSymbolsToBugsnag(
      apiKey: "71b**************867",
      dsymPath: ["com.vjeton.diamond-1.0-25.dSYM.zip"]
    )
```

What I find especially strange is that when I call `fastlane action upload_symbols_to_bugsnag` the files are actually detected just fine:

```
+----------------------+---------------------------+---------------------------+---------------------------+
|                                    upload_symbols_to_bugsnag Options                                     |
+----------------------+---------------------------+---------------------------+---------------------------+
| Key                  | Description               | Env Var(s)                | Default                   |
+----------------------+---------------------------+---------------------------+---------------------------+
| api_key              | Bugsnag API Key           | BUGSNAG_API_KEY           |                           |
| dsym_path            | Path to the DSYM          | BUGSNAG_DSYM_PATH         | ["./com.vjeton.diamond-1  |
|                      | directory, file, or zip   |                           | .0-17.dSYM.zip",          |
|                      | to upload                 |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-18.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-19.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-20.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-21.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-22.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-23.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0-25.dSYM.zip",           |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0.1-26.dSYM.zip",         |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0.1-27.dSYM.zip",         |
|                      |                           |                           | "./com.vjeton.diamond-1.  |
|                      |                           |                           | 0.1-28.dSYM.zip"]
```

It'd be really convenient for me if the files could be detected automatically. :)

Kind regards
Mario

**Comment by xander-jones** [comment]
> Sadly using [".\"] doesn't work for me either:

Whilst the output log looks like you used `["./"]`, just checking if this was a typo on the GitHub comment, or whether this caused an issue.

Do your dSYMs live in `/Users/mario/Repository/VJeton` once downloaded? This is where the plugin is currently looking. From your output log:
```
Uploading files to https://upload.bugsnag.com
INFO [2021-08-27 23:02:12.62]: Uploaded dSYMs in ./
```
It looks like the plugin's looking in the directory above, not finding any dSYMs and then just moving on.

One other thought, if you're using bitcode, you may need to wait for dSYMs to finish processing in your download_dsyms action first ([`wait_for_dsym_processing` flag](https://docs.fastlane.tools/actions/download_dsyms/#parameters))

FWIW: I've tested with a fresh Fastlane.swift integration. `$ fastlane init swift`, installed the fastlane plugins (v2.1.0) with `$ fastlane add_plugin bugsnag` and then added a simple lane

```swift
	func releaseLane() {
		desc("Uploads dSYMs to Bugsnag")
		uploadSymbolsToBugsnag(dsymPath:["./dsyms_test_ok"])
	}
```

This works as expected:

```
$ bundle exec fastlane release --verbose

[✔] 🚀 
DEBUG [2021-09-02 11:51:35.99]: Checking if there are any plugins that should be loaded...
DEBUG [2021-09-02 11:51:36.00]: Loading 'fastlane-plugin-bugsnag' plugin
INFO [2021-09-02 11:51:36.00]: gem 'fastlane-plugin-bugsnag' is already installed
+-------------------------+---------+--------------------------------------------------+
|                                     Used plugins                                     |
+-------------------------+---------+--------------------------------------------------+
| Plugin                  | Version | Action                                           |
+-------------------------+---------+--------------------------------------------------+
| fastlane-plugin-bugsnag | 2.1.0   | upload_symbols_to_bugsnag, send_build_to_bugsnag |
+-------------------------+---------+--------------------------------------------------+
...
@method_name="upload_symbols_to_bugsnag", @class_name=nil, @command_id="", @args=[named argument: dsym_path, value: ["./dsyms_test_ok"], type: , named argument: project_root, value: /Users/xanderjones/GitHub/my-bugsnag-examples/cocoa/ios/fastlane-testing/swift-ios-swift-fastlane, type: , named argument: config_file, value: ./bugsnag-example/Info.plist, type: ]>
INFO [2021-09-02 11:51:41.67]: ---------------------------------------
INFO [2021-09-02 11:51:41.67]: --- Step: upload_symbols_to_bugsnag ---
INFO [2021-09-02 11:51:41.67]: ---------------------------------------
INFO [2021-09-02 11:51:41.67]: Using the API Key from ./bugsnag-example/Info.plist
DEBUG [2021-09-02 11:51:41.67]: Uploading dSYMs to Bugsnag with the following parameters:
DEBUG [2021-09-02 11:51:41.67]:            dsym_path: ["./dsyms_test_ok"]
DEBUG [2021-09-02 11:51:41.67]:         project_root: /Users/xanderjones/GitHub/my-bugsnag-examples/cocoa/ios/fastlane-testing/swift-ios-swift-fastlane
DEBUG [2021-09-02 11:51:41.67]:          config_file: ./bugsnag-example/Info.plist
DEBUG [2021-09-02 11:51:41.67]:              api_key: 
DEBUG [2021-09-02 11:51:41.67]:           upload_url: 
DEBUG [2021-09-02 11:51:41.67]:     symbol_maps_path: 
DEBUG [2021-09-02 11:51:41.67]:   ignore_missing_dwarf: false
DEBUG [2021-09-02 11:51:41.67]:    ignore_empty_dsym: false
Uploading files to https://upload.bugsnag.com
Preparing to upload ./dsyms_test_ok/Bugsnag.framework.dSYM
Uploading UUID: E599CF69-D848-3ED2-9093-68A44234CFCF (armv7) ./dsyms_test_ok/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag UUID: 40112A5E-4A23-37EC-9A5D-95AF2C18AE39 (arm64) ./dsyms_test_ok/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag

1 file(s) uploaded successfully
INFO [2021-09-02 11:51:44.85]: Uploaded dSYMs in ./dsyms_test_ok
DEBUG [2021-09-02 11:51:44.85]: return_value_type is nil value: ["./dsyms_test_ok"]
DEBUG [2021-09-02 11:51:44.85]: sending {"payload":{"status":"ready_for_next","return_object":["./dsyms_test_ok"],"closure_argument_value":""}}
DEBUG [2021-09-02 11:51:44.85]: received done signal shutting down

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | upload_symbols_to_bugsnag | 3           |
+------+---------------------------+-------------+

DEBUG [2021-09-02 11:51:44.86]: All plugins are up to date
INFO [2021-09-02 11:51:44.86]: fastlane.tools finished successfully 🎉
DEBUG [2021-09-02 11:51:44.86]: All plugins are up to date
```

**Comment by RyuX51** [comment]
Thank you for responding to me.

> Whilst the output log looks like you used ["./"], just checking if this was a typo on the GitHub comment, or whether this caused an issue.

It indeed was. Sorry for that. I used `["./"]` as you told me to.

> Do your dSYMs live in /Users/mario/Repository/VJeton once downloaded? This is where the plugin is currently looking.

Yes, they do.

> One other thought, if you're using bitcode, you may need to wait for dSYMs to finish processing in your download_dsyms action first (wait_for_dsym_processing flag)

I tried adding `waitForDsymProcessing: true` but it didn't make a difference.

> FWIW: I've tested with a fresh Fastlane.swift integration. $ fastlane init swift, installed the fastlane plugins (v2.1.0) with $ fastlane add_plugin bugsnag and then added a simple lane

So I just tried the same. removed `fastlane/` and `Gemfile*`, started anew. Used a simple lane

```
func bugsnagLane() {
  uploadSymbolsToBugsnag(
    apiKey: "71b**************867",
    dsymPath:["./dsyms"]
  )
}
```

while having dsyms in the `/Users/mario/Repository/VJeton/dsyms` to be as near as possible on your steps.

```
INFO [2021-09-02 13:52:11.69]: ---------------------------------------
INFO [2021-09-02 13:52:11.69]: --- Step: upload_symbols_to_bugsnag ---
INFO [2021-09-02 13:52:11.69]: ---------------------------------------
DEBUG [2021-09-02 13:52:11.69]: Uploading dSYMs to Bugsnag with the following parameters:
DEBUG [2021-09-02 13:52:11.69]:              api_key: 71b**************867
DEBUG [2021-09-02 13:52:11.69]:            dsym_path: ["./dsyms"]
DEBUG [2021-09-02 13:52:11.69]:         project_root: /Users/mario/Repository/VJeton
DEBUG [2021-09-02 13:52:11.69]:           upload_url:
DEBUG [2021-09-02 13:52:11.69]:     symbol_maps_path:
DEBUG [2021-09-02 13:52:11.69]:   ignore_missing_dwarf: false
DEBUG [2021-09-02 13:52:11.69]:    ignore_empty_dsym: false
DEBUG [2021-09-02 13:52:11.69]:          config_file:
Uploading files to https://upload.bugsnag.com
INFO [2021-09-02 13:52:11.70]: Uploaded dSYMs in ./dsyms
DEBUG [2021-09-02 13:52:11.70]: return_value_type is nil value: ["./dsyms"]
DEBUG [2021-09-02 13:52:11.70]: sending {"payload":{"status":"ready_for_next","return_object":["./dsyms"],"closure_argument_value":""}}
DEBUG [2021-09-02 13:52:11.70]: received done signal shutting down

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | upload_symbols_to_bugsnag | 0           |
+------+---------------------------+-------------+

DEBUG [2021-09-02 13:52:11.72]: All plugins are up to date
INFO [2021-09-02 13:52:11.72]: fastlane.tools finished successfully 🎉
DEBUG [2021-09-02 13:52:11.72]: All plugins are up to date
~/Repository/VJeton develop *1 !36 ?2 ❯ l dsyms                                                         12s 01:52:11 PM
❯ l dsyms
total 81776
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-17.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-18.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-19.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-20.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-21.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-22.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-23.dSYM.zip
-rw-r--r-- 1 mario staff 3.3M  2 Sep   13:44  com.vjeton.diamond-1.0-25.dSYM.zip
-rw-r--r-- 1 mario staff 3.5M  2 Sep   13:44  com.vjeton.diamond-1.0.1-26.dSYM.zip
-rw-r--r-- 1 mario staff 3.5M  2 Sep   13:44  com.vjeton.diamond-1.0.1-27.dSYM.zip
-rw-r--r-- 1 mario staff 3.5M  2 Sep   13:44  com.vjeton.diamond-1.0.1-28.dSYM.zip
-rw-r--r-- 1 mario staff 3.5M  2 Sep   13:44  com.vjeton.diamond-1.0.1-29.dSYM.zip
```

I tried `["./dsyms/"]`, too. Without success.
Using a path to a single file like `dsymPath:["./dsyms/com.vjeton.diamond-1.0.1-29.dSYM.zip"]` works without a problem, so the path is correct.

I don't understand why it's working for you but not for me. 🙁

**Comment by xander-jones** [comment]
Been able to replicate this issue @RyuX51, it's the fact that your dSYMs are zipped and mine not. Taking a look into this now.

**Comment by RyuX51** [comment]
I was a little curious and peeked into it myself. I ended up adding the missing code to `bugsnag-dsym-upload/bin/bugsnag-dsym-upload` which works just fine for me. I also tried it with the extracted dSYMs, still works. Maybe this saves you some time. :)

<img width="952" alt="bugsnag-dsym-upload" src="https://user-images.githubusercontent.com/1900479/131920954-0201d474-2e29-46bc-b4f7-e2377bff22f1.png">

For copy and pasting:

```
for dsym in $(find $dsym_dir -name "*.dSYM" -o -name "*.dSYM.zip" ! -path "*/__MACOSX/*"); do
    log_verbose "Preparing to upload $dsym"

    # if it's a zip file: extract.
    if [[ $dsym == *".zip" ]]; then
        if [[ ! -x "$(command -v unzip 2>/dev/null)" ]]; then
            exit_with_usage "unzip command not found."
        fi
        temp_dir=$(mktemp -dt "bugsnag-dsym-upload.XXX")
        log "[INFO] Extracting $dsym o $temp_dir...";
        unzip -qq $dsym -d $temp_dir
        dsym=$(find $temp_dir -name "*.dSYM")
    fi
```

```
./bugsnag-dsym-upload --api-key 71b**************867 .
[INFO] Extracting ./com.vjeton.diamond-1.0-18.dSYM.zip o /var/folders/n9/g0lr6yb528559m01m41j36n40000gn/T/bugsnag-dsym-upload.XXX.2oeJSae6...
Uploading UUID: 645FC869-B196-30A0-A549-5AD167CE8CEE (arm64) /var/folders/n9/g0lr6yb528559m01m41j36n40000gn/T/bugsnag-dsym-upload.XXX.2oeJSae6/645fc869-b196-30a0-a549-5ad167ce8cee.dSYM/Contents/Resources/DWARF/Diamond
...
[INFO] Extracting ./com.vjeton.diamond-1.0-17.dSYM.zip o /var/folders/n9/g0lr6yb528559m01m41j36n40000gn/T/bugsnag-dsym-upload.XXX.6SwKmPDw...
Uploading UUID: F60A2984-056A-3CBE-AC53-7FB8E29F2D0B (arm64) /var/folders/n9/g0lr6yb528559m01m41j36n40000gn/T/bugsnag-dsym-upload.XXX.6SwKmPDw/f60a2984-056a-3cbe-ac53-7fb8e29f2d0b.dSYM/Contents/Resources/DWARF/Diamond

12 file(s) uploaded successfully
```

**Comment by xander-jones** [comment]
Thanks @RyuX51! We plan to attack this from a slightly different angle, but until then this looks like a reasonable workaround – and in fact this change might be worth including too. A big thank you for the detailed reports & comments :)

**Comment by RyuX51** [comment]
My pleasure. Thank you for your support. I don't know if you want to close this issue now, so I leave it to you. Thanks for this valuable lane and stay healthy.

**Comment by xander-jones** [comment]
Hey @RyuX51, a change has been released in https://github.com/bugsnag/bugsnag-dsym-upload/releases/tag/v2.2.0 which should resolve this issue for you! It'll now upload dSYMs from the search path, and any SharedValues from `gym` and `download_dsyms` actions.

**Comment by RyuX51** [comment]
Yep, I noticed. 😊 I already tried it and can confirm that it's working like a charm now. Thank you again for this quick update, fine sir.

**Comment by RyuX51** [comment]
One problem remains though. It's a little special but maybe you have an answer for this, too.

My project has several targets, which build flavors of the app. After I successfully ran your lane for one target, it's not possible to run it again for another target without completely reinitializing fastlane again. Something in this pipeline (that's actually only `downloadDsyms` and `uploadSymbolsToBugsnag`) seems to "remember" the old files. In this following example, I've already successfully uploaded the dsyms for  `com.vjeton.diamond-1.0-X.dSYM.zip` and try to upload `com.vjeton.diamond-1.0-X.dSYM.zip` afterward. That's not possible without reinitializing fastlane. The same vice versa. I tried it several times.

```
[11:30:17]: Looking for dSYM files for 'lu.apps.VJeton' on platform IOS
[11:30:20]: 🔑  Successfully downloaded dSYM file for 1.0 - 29 to 'lu.apps.VJeton-1.0-29.dSYM.zip'
[11:30:24]: 🔑  Successfully downloaded dSYM file for 1.0 - 18 to 'lu.apps.VJeton-1.0-18.dSYM.zip'
[11:30:25]: 🔑  Successfully downloaded dSYM file for 1.0 - 17 to 'lu.apps.VJeton-1.0-17.dSYM.zip'
[11:30:26]: 🔑  Successfully downloaded dSYM file for 1.0 - 16 to 'lu.apps.VJeton-1.0-16.dSYM.zip'
[11:30:29]: 🔑  Successfully downloaded dSYM file for 1.0 - 15 to 'lu.apps.VJeton-1.0-15.dSYM.zip'
[11:30:30]: 🔑  Successfully downloaded dSYM file for 1.0 - 14 to 'lu.apps.VJeton-1.0-14.dSYM.zip'
[11:30:31]: 🔑  Successfully downloaded dSYM file for 1.0 - 13 to 'lu.apps.VJeton-1.0-13.dSYM.zip'
[11:30:32]: 🔑  Successfully downloaded dSYM file for 1.0 - 12 to 'lu.apps.VJeton-1.0-12.dSYM.zip'
[11:30:34]: 🔑  Successfully downloaded dSYM file for 1.0 - 10 to 'lu.apps.VJeton-1.0-10.dSYM.zip'
[11:30:35]: 🔑  Successfully downloaded dSYM file for 1.0 - 9 to 'lu.apps.VJeton-1.0-9.dSYM.zip'
[11:30:36]: 🔑  Successfully downloaded dSYM file for 1.0 - 6 to 'lu.apps.VJeton-1.0-6.dSYM.zip'
[11:30:40]: 🔑  Successfully downloaded dSYM file for 1.0 - 5 to 'lu.apps.VJeton-1.0-5.dSYM.zip'
[11:30:40]: 🔑  Successfully downloaded dSYM file for 1.0 - 4 to 'lu.apps.VJeton-1.0-4.dSYM.zip'
[11:30:45]: 🔑  Successfully downloaded dSYM file for 1.0 - 3 to 'lu.apps.VJeton-1.0-3.dSYM.zip'
[11:30:45]: 🔑  Successfully downloaded dSYM file for 1.0 - 2 to 'lu.apps.VJeton-1.0-2.dSYM.zip'
[11:30:46]: 🔑  Successfully downloaded dSYM file for 1.0 - 1 to 'lu.apps.VJeton-1.0-1.dSYM.zip'
[11:30:46]: Error setting value '["./com.vjeton.diamond-1.0-17.dSYM.zip", "./com.vjeton.diamond-1.0-18.dSYM.zip", "./com.vjeton.diamond-1.0-19.dSYM.zip", "./com.vjeton.diamond-1.0-20.dSYM.zip", "./com.vjeton.diamond-1.0-21.dSYM.zip", "./com.vjeton.diamond-1.0-22.dSYM.zip", "./com.vjeton.diamond-1.0-23.dSYM.zip", "./com.vjeton.diamond-1.0-25.dSYM.zip", "./com.vjeton.diamond-1.0.1-26.dSYM.zip", "./com.vjeton.diamond-1.0.1-27.dSYM.zip", "./com.vjeton.diamond-1.0.1-28.dSYM.zip", "./com.vjeton.diamond-1.0.1-29.dSYM.zip", "./com.vjeton.diamond-1.0.2-30.dSYM.zip", "./com.vjeton.diamond-1.0.2-31.dSYM.zip", "./com.vjeton.diamond-1.0.2-32.dSYM.zip", "./com.vjeton.diamond-1.0.2-33.dSYM.zip", "./com.vjeton.diamond-1.0.2-34.dSYM.zip", "./com.vjeton.diamond-1.0.3-35.dSYM.zip"]' for option 'dsym_path'
[11:30:46]: You passed invalid parameters to 'upload_symbols_to_bugsnag'.
[11:30:46]: Check out the error below and available options by running `fastlane action upload_symbols_to_bugsnag`
#<Thread:0x00007ff0015c8f70 /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at '{ "commandType": "action", "command": {"commandID" : "","methodName" : "clean_build_artifacts"} }' (JSON::ParserError)
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	from /Users/mario/.gem/gems/fastlane-2.194.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
+---------------------------+-------------------------------------------------------------------+
|                                         Lane Context                                          |
+---------------------------+-------------------------------------------------------------------+
| LANE_NAME                 | bugsnagVJeton                                                     |
| DSYM_PATHS                | ["/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-29.dSYM.zip"  |
|                           | ,                                                                 |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-18.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-17.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-16.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-15.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-14.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-13.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-12.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-10.dSYM.zip",  |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-9.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-6.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-5.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-4.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-3.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-2.dSYM.zip",   |
|                           | "/Users/mario/Repository/VJeton/lu.apps.VJeton-1.0-1.dSYM.zip"]   |
| DSYM_LATEST_UPLOADED_DATE | 2021-08-27T01:01:18-07:00                                         |
+---------------------------+-------------------------------------------------------------------+
[11:30:46]: 809: unexpected token at '{ "commandType": "action", "command": {"commandID" : "","methodName" : "clean_build_artifacts"} }'

+------+----------------+-------------+
|          fastlane summary           |
+------+----------------+-------------+
| Step | Action         | Time (in s) |
+------+----------------+-------------+
| 1    | download_dsyms | 43          |
+------+----------------+-------------+

[11:30:46]: fastlane finished with errors
```

**Comment by xander-jones** [comment]
Hey @RyuX51, are you running multiple lanes in one call to Fastlane? (As described here https://docs.fastlane.tools/advanced/lanes/#switching-lanes)

Would it be possible to see a copy of your `Fastfile`, and how are you calling the lanes to be run in the first place?

**Comment by RyuX51** [comment]
@xander-jones I sent you an email where I attached my Fastfile. At this point, I think it’s something I’m doing wrong, so if you don’t have the time to look into this further I can understand that completely.

**Comment by RyuX51** [comment]
Does this give you any information?

```
INFO [2021-10-05 10:41:43.23]: ---------------------------------------
INFO [2021-10-05 10:41:43.23]: --- Step: upload_symbols_to_bugsnag ---
INFO [2021-10-05 10:41:43.23]: ---------------------------------------
DEBUG [2021-10-05 10:41:43.23]: Uploading dSYMs to Bugsnag with the following parameters:
DEBUG [2021-10-05 10:41:43.23]:                          api_key: f8****************************9f
DEBUG [2021-10-05 10:41:43.23]:                        dsym_path: []
DEBUG [2021-10-05 10:41:43.23]:                     project_root: /Users/mario/Repository/VJeton
DEBUG [2021-10-05 10:41:43.23]:                       upload_url:
DEBUG [2021-10-05 10:41:43.23]:                 symbol_maps_path:
DEBUG [2021-10-05 10:41:43.23]:             ignore_missing_dwarf: false
DEBUG [2021-10-05 10:41:43.23]:                ignore_empty_dsym: false
DEBUG [2021-10-05 10:41:43.23]:                      config_file:
DEBUG [2021-10-05 10:41:43.23]:         SharedValues::DSYM_PATHS: ["/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-43.dSYM.zip", "/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-42.dSYM.zip", "/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-41.dSYM.zip", "/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-39.dSYM.zip"]
DEBUG [2021-10-05 10:41:43.23]:   SharedValues::DSYM_OUTPUT_PATH: not set
DEBUG [2021-10-05 10:41:43.23]: return_value_type is nil value: []
DEBUG [2021-10-05 10:41:43.23]: sending {"payload":{"status":"ready_for_next","return_object":[],"closure_argument_value":""}}
DEBUG [2021-10-05 10:41:43.23]: received command:#<Fastlane::ActionCommand:0x00007f8a6226ff40 @method_name="clean_build_artifacts", @class_name=nil, @command_id="", @args=[]>
INFO [2021-10-05 10:41:43.25]: -----------------------------------
INFO [2021-10-05 10:41:43.25]: --- Step: clean_build_artifacts ---
INFO [2021-10-05 10:41:43.25]: -----------------------------------
DEBUG [2021-10-05 10:41:43.25]: Cleaning up '/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-43.dSYM.zip'
DEBUG [2021-10-05 10:41:43.25]: Cleaning up '/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-42.dSYM.zip'
DEBUG [2021-10-05 10:41:43.25]: Cleaning up '/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-41.dSYM.zip'
DEBUG [2021-10-05 10:41:43.25]: Cleaning up '/Users/mario/Repository/VJeton/com.vjeton.topin-1.0-39.dSYM.zip'
INFO [2021-10-05 10:41:43.25]: Cleaned up build artifacts 🐙
DEBUG [2021-10-05 10:41:43.25]: return_value_type is nil value: true
DEBUG [2021-10-05 10:41:43.25]: sending {"payload":{"status":"ready_for_next","return_object":true,"closure_argument_value":""}}
DEBUG [2021-10-05 10:41:43.25]: received done signal shutting down

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | download_dsyms            | 30          |
| 2    | upload_symbols_to_bugsnag | 0           |
| 3    | clean_build_artifacts     | 0           |
+------+---------------------------+-------------+
```
